version: "2"
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT_HTTP}:80'
      - '${PORT_HTTPS}:443'
      - '${PORT_SSH}:22'
    volumes:
      - ../:/app/
      - ./:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    environment:
      - VIRTUAL_HOST=.app.boilerplate.docker
      - VIRTUAL_PORT=80
      - POSTFIX_RELAYHOST=[mail]:1025

